# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CameraDemo' do
  pod 'AFNetworking', '~> 3.1.0'
pod "Qiniu"
pod 'PINCache', '~> 3.0.1-beta.5'

end
